#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Build the site
pnpm run build:site

# Run ESLint and Prettier on all files to ensure no bad commits
pnpm lint-fix
pnpm format-check

# navigate into the build output directory & Add a cname file
# to ensure Github picks up and sets it to the right domain on deploy
cd dist
echo 'musicchartmaker.com' > CNAME

# add any changed files from the build
git add -A