# Does a lint and format check then builds and deploys when there's a merge to master
name: Deploy to github pages

on:
  push:
    branches: [main]

jobs:
  Check_and_Publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Read the pnpm version from the `.pnpmrc` file
      - name: Read .pnpmrc
        id: pnpm_version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.pnpmrc

      - name: Cache PNPM modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-

      - uses: pnpm/action-setup@v4
        with:
          version: '${{ steps.pnpm_version.outputs.content }}'

      - uses: actions/setup-node@v4
        with:
          # use the output from the action
          node-version-file: '.nvmrc'

      - name: Install `node_modules`
        run: pnpm install

      - name: Checks
        run: pnpm checks

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: gh-pages
          folder: dist