# Runs Type, Format, and Lint checks on all PRs
name: PR Check

on:
  pull_request:

jobs:
  PR_Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install `node_modules`
        run: pnpm install

      - name: Checks
        run: pnpm checks
